// Compact IELTS vocabulary: each entry is [id, word, chinese, phonetic, pos, example, exampleCN, level, topic]
// Grouped by CEFR level. All words are within IELTS exam scope.
// Sources: AWL (Academic Word List), IELTS高频词, 雅思口语/听力/写作/阅读真题词汇

import type { CEFRLevel } from '@/types/user';

export interface VocabWord {
  id: string; word: string; chinese: string; phonetic: string; pos: string;
  example: string; exampleCN: string; level: CEFRLevel; topic: string;
}

type Raw = [string,string,string,string,string,string,string,CEFRLevel,string];
const raw: Raw[] = [
['awl301','norm','规范','/nɔːrm/','n.','Cultural norms vary by country.','文化规范因国家而异。','B1','awl'],
  ['awl302','notion','观念','/ˈnoʊʃən/','n.','I reject the notion that money is everything.','我反对金钱至上的观念。','B2','awl'],
  ['awl303','objective','目标','/əbˈdʒektɪv/','n.','What is your main objective?','你的主要目标是什么？','B1','awl'],
  ['awl304','obtain','获得','/əbˈteɪn/','v.','How can I obtain a visa?','我怎样才能获得签证？','B1','awl'],
  ['awl305','obvious','明显的','/ˈɒbviəs/','adj.','The answer is obvious.','答案很明显。','B1','awl'],
  ['awl306','occupy','占据','/ˈɒkjupaɪ/','v.','Work occupies most of my time.','工作占据了我大部分时间。','B1','awl'],
  ['awl307','offset','抵消','/ˈɒfset/','v.','The gains offset the losses.','收益抵消了损失。','B2','awl'],
  ['awl308','ongoing','持续的','/ˈɒnɡoʊɪŋ/','adj.','The investigation is ongoing.','调查正在进行中。','B1','awl'],
  ['awl309','option','选择','/ˈɒpʃən/','n.','We have several options.','我们有几种选择。','A2','awl'],
  ['awl310','outcome','结果','/ˈaʊtkʌm/','n.','What will be the outcome?','结果会是什么？','B1','awl'],
  ['awl311','output','产出','/ˈaʊtpʊt/','n.','The factory increased its output.','工厂提高了产量。','B1','awl'],
  ['awl312','overall','总体的','/ˌoʊvərˈɔːl/','adj.','The overall result was positive.','总体结果是积极的。','B1','awl'],
  ['awl313','overlap','重叠','/ˌoʊvərˈlæp/','v.','The two topics overlap.','这两个话题有重叠。','B2','awl'],
  ['awl314','paradigm','范式','/ˈpærədaɪm/','n.','We need a paradigm shift.','我们需要范式转变。','C1','awl'],
  ['awl315','parallel','平行的','/ˈpærəlel/','adj.','These two developments are parallel.','这两个发展是平行的。','B2','awl'],
  ['awl316','participate','参与','/pɑːrˈtɪsɪpeɪt/','v.','Everyone should participate.','每个人都应该参与。','B1','awl'],
  ['awl317','passive','被动的','/ˈpæsɪv/','adj.','Passive learning is less effective.','被动学习效果较差。','B2','awl'],
  ['awl318','perceive','感知','/pərˈsiːv/','v.','How do you perceive this situation?','你怎么看待这个情况？','B1','awl'],
  ['awl319','persist','坚持/持续','/pərˈsɪst/','v.','The problem persists.','问题持续存在。','B1','awl'],
  ['awl320','perspective','视角','/pərˈspektɪv/','n.','Try a different perspective.','试试不同的视角。','B2','awl'],
  ['awl321','phase','阶段','/feɪz/','n.','We are entering a new phase.','我们正在进入一个新阶段。','B1','awl'],
  ['awl322','phenomenon','现象','/fɪˈnɒmɪnən/','n.','This is a natural phenomenon.','这是一个自然现象。','B2','awl'],
  ['awl323','pose','构成/摆姿势','/poʊz/','v.','Pollution poses a threat to health.','污染对健康构成威胁。','B1','awl'],
  ['awl324','precise','精确的','/prɪˈsaɪs/','adj.','We need precise measurements.','我们需要精确的测量。','B1','awl'],
  ['awl325','predict','预测','/prɪˈdɪkt/','v.','It is impossible to predict the future.','预测未来是不可能的。','B1','awl'],
  ['awl326','preliminary','初步的','/prɪˈlɪmɪnəri/','adj.','The preliminary results are encouraging.','初步结果令人鼓舞。','B2','awl'],
  ['awl327','priority','优先事项','/praɪˈɒrəti/','n.','Education should be a top priority.','教育应该是头等优先事项。','B1','awl'],
  ['awl328','professional','专业的','/prəˈfeʃənəl/','adj.','She is very professional.','她非常专业。','B1','awl'],
  ['awl329','prohibit','禁止','/prəˈhɪbɪt/','v.','Smoking is prohibited here.','这里禁止吸烟。','B2','awl'],
  ['awl330','promote','促进','/prəˈmoʊt/','v.','Exercise promotes good health.','锻炼促进健康。','B1','awl'],
  ['awl331','proportion','比例','/prəˈpɔːrʃən/','n.','A small proportion of students failed.','一小部分学生不及格。','B1','awl'],
  ['awl332','prospect','前景','/ˈprɒspekt/','n.','The prospects for growth are good.','增长前景良好。','B1','awl'],
  ['awl333','psychology','心理学','/saɪˈkɒlədʒi/','n.','Psychology helps us understand behaviour.','心理学帮助我们理解行为。','B1','awl'],
  ['awl334','publish','出版','/ˈpʌblɪʃ/','v.','The study was published last year.','这项研究去年发表了。','B1','awl'],
  ['awl335','pursue','追求','/pərˈsjuː/','v.','Pursue your dreams.','追求你的梦想。','B1','awl'],
  ['awl336','quote','引用','/kwoʊt/','v.','He quoted a famous scientist.','他引用了一位著名科学家的话。','B1','awl'],
  ['awl337','radical','根本的/激进的','/ˈrædɪkəl/','adj.','We need radical changes.','我们需要根本性的变革。','B2','awl'],
  ['awl338','random','随机的','/ˈrændəm/','adj.','The sample was randomly selected.','样本是随机选取的。','B1','awl'],
  ['awl339','ratio','比率','/ˈreɪʃioʊ/','n.','The ratio of men to women is 3:2.','男女比例是3:2。','B1','awl'],
  ['awl340','rational','理性的','/ˈræʃənəl/','adj.','We must make rational decisions.','我们必须做出理性决策。','B2','awl'],
  ['awl341','react','反应','/riˈækt/','v.','How did they react to the news?','他们对消息有什么反应？','B1','awl'],
  ['awl342','recover','恢复','/rɪˈkʌvər/','v.','The economy is recovering slowly.','经济正在缓慢恢复。','B1','awl'],
  ['awl343','refine','精炼/改进','/rɪˈfaɪn/','v.','We need to refine our approach.','我们需要改进我们的方法。','B2','awl'],
  ['awl344','register','登记','/ˈredʒɪstər/','v.','Please register before the deadline.','请在截止日期前登记。','B1','awl'],
  ['awl345','reinforce','加强','/ˌriːɪnˈfɔːrs/','v.','This reinforces my point.','这加强了我的论点。','B2','awl'],
  ['awl346','reject','拒绝','/rɪˈdʒekt/','v.','The proposal was rejected.','提案被拒绝了。','B1','awl'],
  ['awl347','release','释放/发布','/rɪˈliːs/','v.','The report will be released next week.','报告将于下周发布。','B1','awl'],
  ['awl348','reluctant','不情愿的','/rɪˈlʌktənt/','adj.','She was reluctant to leave.','她不情愿离开。','B2','awl'],
  ['awl349','rely','依赖','/rɪˈlaɪ/','v.','We rely on technology too much.','我们过度依赖技术。','B1','awl'],
  ['awl350','remove','移除','/rɪˈmuːv/','v.','Remove the obstacles.','移除障碍。','B1','awl'],
  ['awl351','resident','居民','/ˈrezɪdənt/','n.','Local residents opposed the plan.','当地居民反对这个计划。','B1','awl'],
  ['awl352','resolve','解决','/rɪˈzɒlv/','v.','We must resolve this issue quickly.','我们必须尽快解决这个问题。','B1','awl'],
  ['awl353','restore','恢复','/rɪˈstɔːr/','v.','We must restore the building.','我们必须修复这座建筑。','B2','awl'],
  ['awl354','retain','保留','/rɪˈteɪn/','v.','We need to retain talented staff.','我们需要留住有才干的员工。','B1','awl'],
  ['awl355','reveal','揭示','/rɪˈviːl/','v.','The report revealed serious problems.','报告揭示了严重问题。','B1','awl'],
  ['awl356','revenue','收入','/ˈrevənjuː/','n.','The company generated high revenue.','公司产生了高收入。','B1','awl'],
  ['awl357','reverse','逆转','/rɪˈvɜːrs/','v.','We cannot reverse the damage.','我们无法逆转损害。','B2','awl'],
  ['awl358','revise','修订','/rɪˈvaɪz/','v.','You should revise your essay.','你应该修改你的文章。','B1','awl'],
  ['awl359','revolution','革命','/ˌrevəˈluːʃən/','n.','The digital revolution changed everything.','数字革命改变了一切。','B1','awl'],
  ['awl360','rigid','僵化的','/ˈrɪdʒɪd/','adj.','The rules are too rigid.','规则太僵化了。','B2','awl'],
  ['awl361','route','路线','/ruːt/','n.','What is the best route?','最佳路线是什么？','B1','awl'],
  ['awl362','scenario','情景','/sɪˈnærioʊ/','n.','Consider the worst-case scenario.','考虑最坏情况。','B2','awl'],
  ['awl363','schedule','日程','/ˈʃedjuːl/','n.','What is your schedule today?','你今天日程是什么？','B1','awl'],
  ['awl364','scheme','方案','/skiːm/','n.','The government introduced a new scheme.','政府推出了一个新方案。','B1','awl'],
  ['awl365','scope','范围','/skoʊp/','n.','The scope of the project is too broad.','项目范围太广了。','B1','awl'],
  ['awl366','sequence','顺序','/ˈsiːkwəns/','n.','The events happened in sequence.','事件按顺序发生。','B1','awl'],
  ['awl367','series','系列','/ˈsɪəriːz/','n.','A series of problems occurred.','发生了一系列问题。','B1','awl'],
  ['awl368','shift','转变','/ʃɪft/','n./v.','There has been a shift in public opinion.','公众舆论发生了转变。','B1','awl'],
  ['awl369','signal','信号','/ˈsɪɡnəl/','n.','The data sends a clear signal.','数据发出了明确信号。','B1','awl'],
  ['awl370','simulate','模拟','/ˈsɪmjuleɪt/','v.','The programme simulates real conditions.','程序模拟真实条件。','B2','awl'],
  ['awl371','sole','唯一的','/soʊl/','adj.','He was the sole survivor.','他是唯一的幸存者。','B2','awl'],
  ['awl372','somewhat','有些/稍微','/ˈsʌmwɒt/','adv.','The results were somewhat surprising.','结果有些令人惊讶。','B1','awl'],
  ['awl373','specify','明确说明','/ˈspesɪfaɪ/','v.','Please specify your requirements.','请明确说明你的要求。','B1','awl'],
  ['awl374','sphere','领域/范围','/sfɪər/','n.','This is outside my sphere of expertise.','这超出了我的专业领域。','B2','awl'],
  ['awl375','stable','稳定的','/ˈsteɪbəl/','adj.','The economy is relatively stable.','经济相对稳定。','B1','awl'],
  ['awl376','statistic','统计数据','/stəˈtɪstɪk/','n.','Statistics show a clear trend.','统计数据显示了明确趋势。','B1','awl'],
  ['awl377','status','地位/状态','/ˈsteɪtəs/','n.','What is your current status?','你目前的状态是什么？','B1','awl'],
  ['awl378','straightforward','直接的','/ˌstreɪtˈfɔːrwərd/','adj.','The instructions are straightforward.','说明很简单直接。','B2','awl'],
  ['awl379','stress','压力/强调','/stres/','n./v.','I want to stress this point.','我想强调这一点。','B1','awl'],
  ['awl380','submit','提交','/səbˈmɪt/','v.','Submit your application by Friday.','周五前提交你的申请。','B1','awl'],
  ['awl381','subsequent','随后的','/ˈsʌbsɪkwənt/','adj.','Subsequent events proved him right.','随后的事件证明他是对的。','B2','awl'],
  ['awl382','substitute','替代','/ˈsʌbstɪtjuːt/','n./v.','There is no substitute for hard work.','努力无可替代。','B2','awl'],
  ['awl383','sufficient','足够的','/səˈfɪʃənt/','adj.','Is the evidence sufficient?','证据充分吗？','B2','awl'],
  ['awl384','sum','总和','/sʌm/','n.','The sum of all parts.','各部分的总和。','B1','awl'],
  ['awl385','summary','摘要','/ˈsʌməri/','n.','Give me a brief summary.','给我一个简短的摘要。','B1','awl'],
  ['awl386','supplement','补充','/ˈsʌplɪment/','v./n.','This book supplements the course.','本书补充了课程内容。','B2','awl'],
  ['awl387','suspend','暂停','/səˈspend/','v.','The service was suspended.','服务被暂停了。','B2','awl'],
  ['awl388','sustain','维持','/səˈsteɪn/','v.','Can we sustain this growth?','我们能维持这个增长吗？','B2','awl'],
  ['awl389','symbol','符号/象征','/ˈsɪmbəl/','n.','The dove is a symbol of peace.','鸽子是和平的象征。','B1','awl'],
  ['awl390','target','目标','/ˈtɑːrɡɪt/','n.','We set ambitious targets.','我们设定了雄心勃勃的目标。','B1','awl'],
  ['awl391','technique','技术/技巧','/tekˈniːk/','n.','What technique did you use?','你用了什么技巧？','B1','awl'],
  ['awl392','temporary','临时的','/ˈtempərəri/','adj.','This is only temporary.','这只是暂时的。','B1','awl'],
  ['awl393','tense','紧张的','/tens/','adj.','The atmosphere was tense.','气氛很紧张。','B1','awl'],
  ['awl394','terminate','终止','/ˈtɜːrmɪneɪt/','v.','The contract was terminated.','合同被终止了。','B2','awl'],
  ['awl395','theme','主题','/θiːm/','n.','What is the main theme?','主题是什么？','B1','awl'],
  ['awl396','thereby','从而','/ˌðeərˈbaɪ/','adv.','He saved money, thereby reducing his debt.','他存了钱，从而减少了债务。','B2','awl'],
  ['awl397','thesis','论文/论点','/ˈθiːsɪs/','n.','What is your main thesis?','你的主要论点是什么？','B2','awl'],
  ['awl398','trace','追踪','/treɪs/','v.','We can trace the problem to its source.','我们可以追踪问题的根源。','B1','awl'],
  ['awl399','transform','转变','/trænsˈfɔːrm/','v.','Technology has transformed education.','技术改变了教育。','B1','awl'],
  ['awl400','transmit','传播','/trænzˈmɪt/','v.','The disease can be transmitted easily.','疾病很容易传播。','B2','awl'],
  ['awl401','trend','趋势','/trend/','n.','The trend is clear.','趋势很明显。','B1','awl'],
  ['awl402','trigger','触发','/ˈtrɪɡər/','v.','What triggered this change?','什么触发了这个变化？','B2','awl'],
  ['awl403','ultimate','最终的','/ˈʌltɪmət/','adj.','The ultimate goal is happiness.','最终目标是幸福。','B1','awl'],
  ['awl404','undergo','经历','/ˌʌndərˈɡoʊ/','v.','The system is undergoing changes.','系统正在经历变化。','B2','awl'],
  ['awl405','underline','强调','/ˌʌndərˈlaɪn/','v.','This underlines the importance of education.','这强调了教育的重要性。','B1','awl'],
  ['awl406','undertake','承担','/ˌʌndərˈteɪk/','v.','She undertook a difficult task.','她承担了一项艰巨的任务。','B2','awl'],
  ['awl407','uniform','统一的','/ˈjuːnɪfɔːrm/','adj.','The standards must be uniform.','标准必须是统一的。','B1','awl'],
  ['awl408','unique','独特的','/juːˈniːk/','adj.','Each person is unique.','每个人都是独特的。','B1','awl'],
  ['awl409','utilise','利用','/ˈjuːtɪlaɪz/','v.','We should utilise our resources wisely.','我们应该明智地利用资源。','B2','awl'],
  ['awl410','valid','有效的','/ˈvælɪd/','adj.','Do you have a valid passport?','你有有效护照吗？','B1','awl'],
  ['awl411','vehicle','车辆','/ˈviːɪkəl/','n.','Electric vehicles are becoming popular.','电动汽车正变得流行。','B1','awl'],
  ['awl412','version','版本','/ˈvɜːrʒən/','n.','This is the latest version.','这是最新版本。','B1','awl'],
  ['awl413','via','通过','/ˈvaɪə/','prep.','I sent it via email.','我通过电子邮件发送了。','B1','awl'],
  ['awl414','violate','违反','/ˈvaɪəleɪt/','v.','This violates the rules.','这违反了规则。','B2','awl'],
  ['awl415','virtual','虚拟的','/ˈvɜːrtʃuəl/','adj.','Virtual meetings save time.','虚拟会议节省时间。','B1','awl'],
  ['awl416','visible','可见的','/ˈvɪzɪbəl/','adj.','The change was clearly visible.','变化清晰可见。','B1','awl'],
  ['awl417','vision','愿景','/ˈvɪʒən/','n.','We need a clear vision.','我们需要清晰的愿景。','B1','awl'],
  ['awl418','visual','视觉的','/ˈvɪʒuəl/','adj.','Visual aids help learning.','视觉辅助有助于学习。','B1','awl'],
  ['awl419','volume','容量/卷','/ˈvɒljuːm/','n.','The volume of traffic is increasing.','交通量在增加。','B1','awl'],
  ['awl420','voluntary','自愿的','/ˈvɒləntəri/','adj.','Participation is voluntary.','参与是自愿的。','B1','awl'],
  ['awl421','welfare','福利','/ˈwelfeər/','n.','Animal welfare is a growing concern.','动物福利是一个日益关注的问题。','B1','awl'],
  ['awl422','whereas','然而','/weərˈæz/','conj.','I like tea, whereas he prefers coffee.','我喜欢茶，而他更喜欢咖啡。','B2','awl'],
  ['awl423','widespread','广泛的','/ˈwaɪdspred/','adj.','The problem is widespread.','这个问题很普遍。','B2','awl'],
  ['awl424','yield','产生/产出','/jiːld/','v.','The investment yielded good returns.','投资产生了良好的回报。','B2','awl'],
  ['awl425','zone','区域','/zoʊn/','n.','This is a no-parking zone.','这是禁停区。','B1','awl'],

// A0: Speaking Part 1 基础
['a001','family','家庭','/ˈfæməli/','n.','My family has 5 members — and only one TV remote.','我家有5口人——只有1个电视遥控器。','A0','people'],
['a002','friend','朋友','/frend/','n.','A true friend will help you move a sofa.','真正的朋友会帮你搬沙发。','A0','people'],
['a003','hometown','家乡','/ˈhoʊmtaʊn/','n.','My hometown is so small that even Google Maps asks for directions.','我的家乡太小了，连谷歌地图都要问路。','A0','place'],
['a004','weather','天气','/ˈweðər/','n.','The weather is like my WiFi — unpredictable.','天气就像我的WiFi——无法预测。','A0','daily'],
['a005','hobby','爱好','/ˈhɒbi/','n.','My hobby is collecting hobbies.','我的爱好是收集各种爱好。','A0','daily'],
['a006','music','音乐','/ˈmjuːzɪk/','n.','Music is what feelings sound like.','我每天听音乐。','A0','daily'],
['a007','food','食物','/fuːd/','n.','My favourite food is noodles.','我最喜欢的食物是面条。','A0','daily'],
['a008','student','学生','/ˈstjuːdənt/','n.','I am a university student.','我是一名大学生。','A0','education'],
['a009','teacher','老师','/ˈtiːtʃər/','n.','My favourite teacher was Mr. Li.','我最喜欢的老师是李老师。','A0','education'],
['a010','happy','开心的','/ˈhæpi/','adj.','I am happy when my phone battery is above 80%.','我手机电量超过80%时，我就开心。','A0','feeling'],
['a011','weekend','周末','/ˌwiːkˈend/','n.','I usually relax on weekends.','我周末通常休息。','A0','daily'],
['a012','morning','早晨','/ˈmɔːrnɪŋ/','n.','I wake up early in the morning.','我早晨很早起床。','A0','daily'],
['a013','house','房子','/haʊs/','n.','This is my house.','这是我的房子。','A0','place'],
['a014','room','房间','/ruːm/','n.','My room is small but at least I can touch all four walls from my bed.','我的房间很小，但至少我躺在床上就能碰到四面墙。','A0','place'],
['a015','book','书','/bʊk/','n.','I am reading an interesting book.','我在读一本有趣的书。','A0','daily'],
['a016','water','水','/ˈwɔːtər/','n.','Please give me some water.','请给我一些水。','A0','daily'],
['a017','time','时间','/taɪm/','n.','What time is it?','现在几点了？','A0','daily'],
['a018','work','工作','/wɜːrk/','n./v.','I work in an office.','我在办公室工作。','A0','work'],
['a019','study','学习','/ˈstʌdi/','v.','I study English every day.','我每天学英语。','A0','education'],
['a020','travel','旅行','/ˈtrævəl/','v.','I like to travel to new places.','我喜欢去新的地方旅行。','A0','travel'],

// A1: Listening S1-2 + Basic Academic
['a101','accommodation','住宿','/əˌkɒməˈdeɪʃən/','n.','I need to find accommodation near the university.','我需要在大学附近找住宿。','A1','listening'],
['a102','reservation','预订','/ˌrezərˈveɪʃən/','n.','I have a reservation for two nights.','我预订了两晚。','A1','listening'],
['a103','appointment','预约','/əˈpɔɪntmənt/','n.','I would like to make an appointment.','我想预约。','A1','listening'],
['a104','passenger','乘客','/ˈpæsɪndʒər/','n.','All passengers must show their tickets.','所有乘客必须出示车票。','A1','listening'],
['a105','destination','目的地','/ˌdestɪˈneɪʃən/','n.','Our destination is London.','我们的目的地是伦敦。','A1','listening'],
['a106','departure','出发','/dɪˈpɑːrtʃər/','n.','The departure time is 3 PM.','出发时间是下午3点。','A1','listening'],
['a107','temporary','临时的','/ˈtempərəri/','adj.','Coffee is temporary; knowledge is forever.','这是个临时的解决方案。','A1','academic'],
['a108','improve','改善','/ɪmˈpruːv/','v.','I want to improve my English.','我想提高我的英语水平。','A1','academic'],
['a109','provide','提供','/prəˈvaɪd/','v.','The hotel provides free breakfast.','酒店提供免费早餐。','A1','academic'],
['a110','include','包括','/ɪnˈkluːd/','v.','The price includes tax.','价格包括税。','A1','academic'],
['a111','reduce','减少','/rɪˈdjuːs/','v.','We need to reduce pollution.','我们需要减少污染。','A1','topic'],
['a112','increase','增加','/ɪnˈkriːs/','v.','The number of cars is increasing.','汽车数量在增加。','A1','topic'],
['a113','develop','发展','/dɪˈveləp/','v.','The city is developing rapidly.','城市正在快速发展。','A1','topic'],
['a114','support','支持','/səˈpɔːrt/','v./n.','I support this idea.','我支持这个想法。','A1','academic'],
['a115','suggest','建议','/səˈdʒest/','v.','I suggest we start early.','我建议我们早点开始。','A1','academic'],
['a116','explain','解释','/ɪkˈspleɪn/','v.','Can you explain this to me?','你能给我解释一下吗？','A1','academic'],
['a117','describe','描述','/dɪˈskraɪb/','v.','Describe your hometown.','描述你的家乡。','A1','speaking'],
['a118','opportunity','机会','/ˌɒpəˈtjuːnəti/','n.','This is a great opportunity.','这是一个很好的机会。','A1','topic'],
['a119','experience','经历/经验','/ɪkˈspɪriəns/','n.','She has a lot of experience.','她有很多经验。','A1','topic'],
['a120','benefit','好处','/ˈbenɪfɪt/','n.','Exercise has many benefits.','运动有很多好处。','A1','topic'],

// A2: IELTS 核心话题词汇
['a201','environment','环境','/ɪnˈvaɪrənmənt/','n.','We must protect the environment.','我们必须保护环境。','A2','environment'],
['a202','pollution','污染','/pəˈluːʃən/','n.','Air pollution is a serious problem.','空气污染是一个严重的问题。','A2','environment'],
['a203','climate','气候','/ˈklaɪmət/','n.','The climate is changing rapidly.','气候正在快速变化。','A2','environment'],
['a204','education','教育','/ˌedʒuˈkeɪʃən/','n.','Education is the key to success.','教育是成功的关键。','A2','education'],
['a205','knowledge','知识','/ˈnɒlɪdʒ/','n.','Knowledge is power.','知识就是力量。','A2','education'],
['a206','technology','技术','/tekˈnɒlədʒi/','n.','Technology is changing our lives.','技术正在改变我们的生活。','A2','technology'],
['a207','internet','互联网','/ˈɪntərnet/','n.','The internet connects people worldwide.','互联网连接了全世界的人。','A2','technology'],
['a208','government','政府','/ˈɡʌvərnmənt/','n.','The government should take action.','政府应该采取行动。','A2','society'],
['a209','population','人口','/ˌpɒpjuˈleɪʃən/','n.','The population is growing rapidly.','人口正在快速增长。','A2','society'],
['a210','economy','经济','/ɪˈkɒnəmi/','n.','The economy is improving.','经济正在好转。','A2','society'],
['a211','culture','文化','/ˈkʌltʃər/','n.','Every country has its own culture.','每个国家都有自己的文化。','A2','culture'],
['a212','tradition','传统','/trəˈdɪʃən/','n.','This is an old tradition.','这是一个古老的传统。','A2','culture'],
['a213','health','健康','/helθ/','n.','Health is more important than wealth.','健康比财富更重要。','A2','health'],
['a214','exercise','锻炼','/ˈeksərsaɪz/','n.','Regular exercise is good for health.','经常锻炼有益健康。','A2','health'],
['a215','disease','疾病','/dɪˈziːz/','n.','Heart disease is a major killer.','心脏病是主要的致死原因。','A2','health'],
['a216','global','全球的','/ˈɡloʊbəl/','adj.','Climate change is a global issue.','气候变化是一个全球性问题。','A2','environment'],
['a217','effective','有效的','/ɪˈfektɪv/','adj.','This is an effective method.','这是一个有效的方法。','A2','academic'],
['a218','negative','消极的','/ˈneɡətɪv/','adj.','Social media can have negative effects.','社交媒体可能有负面影响。','A2','academic'],
['a219','affect','影响','/əˈfekt/','v.','How does this affect us?','这如何影响我们？','A2','academic'],
['a220','challenge','挑战','/ˈtʃælɪndʒ/','n.','This is a real challenge.','这是一个真正的挑战。','A2','academic'],

// B1: AWL Sublist 1-5
['b101','analyse','分析','/ˈænəlaɪz/','v.','We need to analyse the data carefully.','我们需要仔细分析数据。','B1','awl'],
['b102','approach','方法','/əˈproʊtʃ/','n.','We need a new approach to this problem.','我们需要一个新方法。','B1','awl'],
['b103','assess','评估','/əˈses/','v.','We need to assess the situation.','我们需要评估情况。','B1','awl'],
['b104','assume','假设','/əˈsjuːm/','v.','Do not assume anything.','不要做任何假设。','B1','awl'],
['b105','context','背景','/ˈkɒntekst/','n.','You need to understand the context.','你需要理解背景。','B1','awl'],
['b106','create','创造','/kriˈeɪt/','v.','Artists create beauty.','艺术家创造美。','B1','awl'],
['b107','data','数据','/ˈdeɪtə/','n.','The data shows a clear trend.','数据显示了明确的趋势。','B1','awl'],
['b108','establish','建立','/ɪˈstæblɪʃ/','v.','They established a new school.','他们建立了一所新学校。','B1','awl'],
['b109','factor','因素','/ˈfæktər/','n.','Cost is an important factor.','成本是一个重要因素。','B1','awl'],
['b110','identify','识别','/aɪˈdentɪfaɪ/','v.','Can you identify the problem?','你能识别问题吗？','B1','awl'],
['b111','indicate','表明','/ˈɪndɪkeɪt/','v.','The results indicate a problem.','结果表明有问题。','B1','awl'],
['b112','involve','涉及','/ɪnˈvɒlv/','v.','The job involves a lot of travel.','这份工作涉及大量出差。','B1','awl'],
['b113','issue','议题','/ˈɪʃuː/','n.','This is a complex issue.','这是一个复杂的问题。','B1','awl'],
['b114','major','主要的','/ˈmeɪdʒər/','adj.','This is a major problem.','这是一个主要问题。','B1','awl'],
['b115','method','方法','/ˈmeθəd/','n.','This method is effective.','这个方法有效。','B1','awl'],
['b116','policy','政策','/ˈpɒləsi/','n.','The government introduced a new policy.','政府出台了一项新政策。','B1','awl'],
['b117','require','需要','/rɪˈkwaɪər/','v.','This job requires experience.','这份工作需要经验。','B1','awl'],
['b118','research','研究','/rɪˈsɜːrtʃ/','n.','More research is needed.','需要更多研究。','B1','awl'],
['b119','significant','显著的','/sɪɡˈnɪfɪkənt/','adj.','There was a significant increase.','有显著的增长。','B1','awl'],
['b120','source','来源','/sɔːrs/','n.','You should cite your sources.','你应该注明来源。','B1','awl'],

// B2: AWL Sublist 6-10
['b201','accurate','准确的','/ˈækjərət/','adj.','We need accurate information.','我们需要准确的信息。','B2','awl-adv'],
['b202','adequate','足够的','/ˈædɪkwət/','adj.','The supply is not adequate.','供应不足。','B2','awl-adv'],
['b203','comprehensive','全面的','/ˌkɒmprɪˈhensɪv/','adj.','We need a comprehensive solution.','我们需要一个全面的解决方案。','B2','awl-adv'],
['b204','controversy','争议','/ˈkɒntrəvɜːrsi/','n.','The policy caused controversy.','这项政策引起了争议。','B2','awl-adv'],
['b205','crucial','至关重要的','/ˈkruːʃəl/','adj.','This decision is crucial.','这个决定至关重要。','B2','awl-adv'],
['b206','demonstrate','展示','/ˈdemənstreɪt/','v.','This demonstrates the importance.','这证明了重要性。','B2','awl-adv'],
['b207','enhance','增强','/ɪnˈhɑːns/','v.','This will enhance your skills.','这将提高你的技能。','B2','awl-adv'],
['b208','hypothesis','假设','/haɪˈpɒθəsɪs/','n.','The hypothesis was supported.','这个假设得到了支持。','B2','awl-adv'],
['b209','implement','实施','/ˈɪmplɪment/','v.','We need to implement the plan.','我们需要实施这个计划。','B2','awl-adv'],
['b210','inevitable','不可避免','/ɪnˈevɪtəbəl/','adj.','Change is inevitable.','变化是不可避免的。','B2','awl-adv'],
['b211','innovation','创新','/ˌɪnəˈveɪʃən/','n.','Innovation drives progress.','创新推动进步。','B2','awl-adv'],
['b212','potential','潜力','/pəˈtenʃəl/','n.','She has great potential.','她有巨大的潜力。','B2','awl-adv'],
['b213','relevant','相关的','/ˈreləvənt/','adj.','Is this relevant to our discussion?','这和我们的讨论相关吗？','B2','awl-adv'],
['b214','resource','资源','/rɪˈzɔːrs/','n.','Natural resources are limited.','自然资源是有限的。','B2','awl-adv'],
['b215','sufficient','足够的','/səˈfɪʃənt/','adj.','Is the evidence sufficient?','证据足够吗？','B2','awl-adv'],
['b216','perspective','视角','/pərˈspektɪv/','n.','Try to see it from a different perspective.','试着从不同的角度看。','B2','awl-adv'],
['b217','priority','优先事项','/praɪˈɒrəti/','n.','Education should be a priority.','教育应该是优先事项。','B2','awl-adv'],
['b218','outcome','结果','/ˈaʊtkʌm/','n.','What will be the outcome?','结果会是什么？','B2','awl-adv'],
['b219','widespread','广泛的','/ˈwaɪdspred/','adj.','The problem is widespread.','这个问题很普遍。','B2','awl-adv'],
['b220','whereas','然而','/weərˈæz/','conj.','I like tea, whereas he prefers coffee.','我喜欢茶，而他更喜欢咖啡。','B2','awl-adv'],

// C1: 高分搭配
['c101','address the issue','解决问题','/əˈdres ðə ˈɪʃuː/','phrase','We must address the issue of climate change.','我们必须应对气候变化问题。','C1','collocation'],
['c102','play a crucial role','发挥关键作用','/pleɪ ə ˈkruːʃəl roʊl/','phrase','Education plays a crucial role in development.','教育在发展中发挥关键作用。','C1','collocation'],
['c103','raise awareness','提高意识','/reɪz əˈweərnəs/','phrase','We need to raise awareness about this issue.','我们需要提高对这个问题的认识。','C1','collocation'],
['c104','take responsibility','承担责任','/teɪk rɪˌspɒnsəˈbɪləti/','phrase','Governments must take responsibility.','政府必须承担责任。','C1','collocation'],
['c105','pose a threat','构成威胁','/poʊz ə θret/','phrase','Pollution poses a threat to health.','污染对健康构成威胁。','C1','collocation'],
['c106','bridge the gap','弥合差距','/brɪdʒ ðə ɡæp/','phrase','We need to bridge the gap between rich and poor.','我们需要弥合贫富差距。','C1','collocation'],
['c107','take into account','考虑到','/teɪk ˈɪntuː əˈkaʊnt/','phrase','We must take all factors into account.','我们必须考虑所有因素。','C1','collocation'],
['c108','give rise to','引起','/ɡɪv raɪz tuː/','phrase','This could give rise to new problems.','这可能导致新的问题。','C1','collocation'],
['c109','in the long run','从长远看','/ɪn ðə lɒŋ rʌn/','phrase','In the long run, this will benefit everyone.','从长远看，这将使所有人受益。','C1','collocation'],
['c110','take measures','采取措施','/teɪk ˈmeʒərz/','phrase','The government should take measures immediately.','政府应立即采取措施。','C1','collocation'],

// ── A0 扩充 ──
['a021','school','学校','/skuːl/','n.','I go to school by bus.','我坐公交上学。','A0','daily'],
['a022','hospital','医院','/ˈhɒspɪtəl/','n.','The hospital is near my house.','医院在我家附近。','A0','place'],
['a023','money','钱','/ˈmʌni/','n.','I need to save money.','我需要存钱。','A0','daily'],
['a024','phone','手机/电话','/foʊn/','n.','I lost my phone.','我手机丢了。','A0','daily'],
['a025','name','名字','/neɪm/','n.','What is your name?','你叫什么名字？','A0','people'],
['a026','city','城市','/ˈsɪti/','n.','Beijing is a big city.','北京是个大城市。','A0','place'],
['a027','country','国家','/ˈkʌntri/','n.','China is my country.','中国是我的国家。','A0','place'],
['a028','language','语言','/ˈlæŋɡwɪdʒ/','n.','I am learning a new language.','我在学一门新语言。','A0','education'],
['a029','animal','动物','/ˈænɪməl/','n.','My favourite animal is a dog.','我最喜欢的动物是狗。','A0','daily'],
['a030','flower','花','/ˈflaʊər/','n.','The flowers are beautiful.','花儿很美。','A0','daily'],
['a031','river','河流','/ˈrɪvər/','n.','There is a river near my house.','我家附近有条河。','A0','place'],
['a032','mountain','山','/ˈmaʊntɪn/','n.','I like climbing mountains.','我喜欢爬山。','A0','place'],
['a033','tree','树','/triː/','n.','There are many trees in the park.','公园里有很多树。','A0','daily'],
['a034','rain','雨','/reɪn/','n.','It is going to rain.','要下雨了。','A0','daily'],
['a035','snow','雪','/snoʊ/','n.','I have never seen snow.','我从没见过雪。','A0','daily'],

// ── A1 扩充 ──
['a121','customer','顾客','/ˈkʌstəmər/','n.','The customer is always right.','顾客永远是对的。','A1','listening'],
['a122','receipt','收据','/rɪˈsiːt/','n.','Please keep your receipt.','请保留收据。','A1','listening'],
['a123','flight','航班','/flaɪt/','n.','My flight is delayed.','我的航班延误了。','A1','listening'],
['a124','luggage','行李','/ˈlʌɡɪdʒ/','n.','Where can I collect my luggage?','我在哪里取行李？','A1','listening'],
['a125','passport','护照','/ˈpæspɔːrt/','n.','Show me your passport, please.','请出示你的护照。','A1','listening'],
['a126','delay','延误/推迟','/dɪˈleɪ/','n./v.','The train was delayed by one hour.','火车延误了一小时。','A1','listening'],
['a127','cancel','取消','/ˈkænsəl/','v.','The meeting was cancelled.','会议被取消了。','A1','academic'],
['a128','attend','参加/出席','/əˈtend/','v.','I will attend the meeting.','我会参加会议。','A1','academic'],
['a129','discuss','讨论','/dɪˈskʌs/','v.','Let us discuss this problem.','我们来讨论这个问题。','A1','academic'],
['a130','prepare','准备','/prɪˈpeər/','v.','I need to prepare for the exam.','我需要准备考试。','A1','education'],
['a131','compare','比较','/kəmˈpeər/','v.','Compare the two options.','比较这两个选项。','A1','academic'],
['a132','consider','考虑','/kənˈsɪdər/','v.','You should consider all factors.','你应该考虑所有因素。','A1','academic'],
['a133','manage','管理/设法','/ˈmænɪdʒ/','v.','How do you manage your time?','你怎么管理时间？','A1','academic'],
['a134','protect','保护','/prəˈtekt/','v.','We must protect the environment.','我们必须保护环境。','A1','topic'],
['a135','encourage','鼓励','/ɪnˈkʌrɪdʒ/','v.','Teachers should encourage students.','老师应该鼓励学生。','A1','education'],

// ── A2 扩充 ──
['a221','attitude','态度','/ˈætɪtjuːd/','n.','A positive attitude is important.','积极的态度很重要。','A2','academic'],
['a222','behaviour','行为','/bɪˈheɪvjər/','n.','Your behaviour affects others.','你的行为影响他人。','A2','society'],
['a223','community','社区/群体','/kəˈmjuːnəti/','n.','We should help our local community.','我们应该帮助本地社区。','A2','society'],
['a224','conflict','冲突','/ˈkɒnflɪkt/','n.','The conflict lasted for years.','冲突持续了多年。','A2','society'],
['a225','demand','需求/要求','/dɪˈmɑːnd/','n.','There is a high demand for teachers.','对教师的需求很高。','A2','society'],
['a226','employment','就业','/ɪmˈplɔɪmənt/','n.','Employment rates are rising.','就业率在上升。','A2','work'],
['a227','freedom','自由','/ˈfriːdəm/','n.','Freedom of speech is essential.','言论自由至关重要。','A2','society'],
['a228','immigrant','移民','/ˈɪmɪɡrənt/','n.','Many immigrants start small businesses.','许多移民创办小企业。','A2','society'],
['a229','income','收入','/ˈɪnkʌm/','n.','He has a high income.','他有高收入。','A2','work'],
['a230','influence','影响','/ˈɪnfluəns/','n./v.','Parents influence their children deeply.','父母深刻影响孩子。','A2','society'],
['a231','pollutant','污染物','/pəˈluːtənt/','n.','Factories release pollutants into the air.','工厂向空气中排放污染物。','A2','environment'],
['a232','renewable','可再生的','/rɪˈnjuːəbəl/','adj.','Solar power is a renewable energy source.','太阳能是可再生能源。','A2','environment'],
['a233','sustainable','可持续的','/səˈsteɪnəbəl/','adj.','Sustainable development is the goal.','可持续发展是目标。','A2','environment'],
['a234','wildlife','野生动物','/ˈwaɪldlaɪf/','n.','We should protect wildlife.','我们应该保护野生动物。','A2','environment'],
['a235','nutrition','营养','/njuːˈtrɪʃən/','n.','Good nutrition is important for health.','良好营养对健康很重要。','A2','health'],

// ── B1 扩充 (AWL 6-10) ──
['b121','access','访问/获取','/ˈækses/','n./v.','Everyone should have access to education.','每个人都应该有受教育的机会。','B1','awl'],
['b122','adjust','调整/适应','/əˈdʒʌst/','v.','We need to adjust our plan.','我们需要调整计划。','B1','awl'],
['b123','alter','改变/修改','/ˈɔːltər/','v.','This will alter the outcome.','这将改变结果。','B1','awl'],
['b124','concentrate','集中/专注','/ˈkɒnsəntreɪt/','v.','I cannot concentrate with noise.','有噪音我无法集中。','B1','awl'],
['b125','conflict','冲突','/ˈkɒnflɪkt/','n.','There is a conflict between the two sides.','双方之间存在冲突。','B1','awl'],
['b126','contribute','贡献/促成','/kənˈtrɪbjuːt/','v.','Everyone can contribute to society.','每个人都能为社会做贡献。','B1','awl'],
['b127','decline','下降/拒绝','/dɪˈklaɪn/','v./n.','The number of smokers is declining.','吸烟者数量在下降。','B1','awl'],
['b128','eliminate','消除/淘汰','/ɪˈlɪmɪneɪt/','v.','We must eliminate poverty.','我们必须消除贫困。','B1','awl'],
['b129','emerge','出现/浮现','/ɪˈmɜːrdʒ/','v.','A new problem has emerged.','一个新问题出现了。','B1','awl'],
['b130','emphasise','强调','/ˈemfəsaɪz/','v.','I want to emphasise this point.','我想强调这一点。','B1','awl'],
['b131','ensure','确保','/ɪnˈʃʊr/','v.','We must ensure safety.','我们必须确保安全。','B1','awl'],
['b132','evaluate','评估/评价','/ɪˈvæljueɪt/','v.','We need to evaluate the results.','我们需要评估结果。','B1','awl'],
['b133','expand','扩展/扩大','/ɪkˈspænd/','v.','The company is expanding rapidly.','公司正在快速扩张。','B1','awl'],
['b134','expose','暴露/揭露','/ɪkˈspoʊz/','v.','The report exposed the truth.','报告揭露了真相。','B1','awl'],
['b135','generate','产生/生成','/ˈdʒenəreɪt/','v.','This could generate new jobs.','这可能创造新就业。','B1','awl'],

// ── B2 扩充 ──
['b221','ambiguous','模糊的/有歧义的','/æmˈbɪɡjuəs/','adj.','The statement was ambiguous.','这个声明含糊不清。','B2','awl-adv'],
['b222','arbitrary','任意的/武断的','/ˈɑːrbɪtrəri/','adj.','The decision seemed arbitrary.','这个决定似乎很武断。','B2','awl-adv'],
['b223','bias','偏见/偏向','/ˈbaɪəs/','n.','The study had a clear bias.','这项研究有明显偏见。','B2','awl-adv'],
['b224','commodity','商品','/kəˈmɒdəti/','n.','Oil is a valuable commodity.','石油是一种有价值的商品。','B2','awl-adv'],
['b225','diminish','减少/削弱','/dɪˈmɪnɪʃ/','v.','The pain will diminish over time.','疼痛会随时间减轻。','B2','awl-adv'],
['b226','discretion','酌情决定/谨慎','/dɪˈskreʃən/','n.','Use your discretion in this matter.','这件事你自己酌情处理。','B2','awl-adv'],
['b227','empirical','经验主义的/实证的','/ɪmˈpɪrɪkəl/','adj.','We need empirical evidence.','我们需要实证证据。','B2','awl-adv'],
['b228','fluctuate','波动/起伏','/ˈflʌktʃueɪt/','v.','Prices fluctuate daily.','价格每天波动。','B2','awl-adv'],
['b229','incorporate','纳入/合并','/ɪnˈkɔːrpəreɪt/','v.','We should incorporate feedback.','我们应该纳入反馈。','B2','awl-adv'],
['b230','infrastructure','基础设施','/ˈɪnfrəstrʌktʃər/','n.','The city needs better infrastructure.','城市需要更好的基础设施。','B2','awl-adv'],
['b231','inherent','固有的/内在的','/ɪnˈhɪərənt/','adj.','There are inherent risks.','存在固有风险。','B2','awl-adv'],
['b232','integration','融合/一体化','/ˌɪntɪˈɡreɪʃən/','n.','Cultural integration takes time.','文化融合需要时间。','B2','awl-adv'],
['b233','intervene','干预/介入','/ˌɪntərˈviːn/','v.','The government should intervene.','政府应该干预。','B2','awl-adv'],
['b234','justify','证明合理/辩护','/ˈdʒʌstɪfaɪ/','v.','How do you justify this decision?','你如何证明这个决定合理？','B2','awl-adv'],
['b235','marginal','边缘的/微小的','/ˈmɑːrdʒɪnəl/','adj.','The difference was marginal.','差异微乎其微。','B2','awl-adv'],

// ── C1 扩充 ──
['c111','it is widely acknowledged','人们普遍认为','/ɪt ɪz ˈwaɪdli əkˈnɒlɪdʒd/','phrase','It is widely acknowledged that education is vital.','人们普遍认为教育至关重要。','C1','collocation'],
['c112','a double-edged sword','双刃剑','/ə ˈdʌbəl edʒd sɔːrd/','phrase','Social media is a double-edged sword.','社交媒体是一把双刃剑。','C1','collocation'],
['c113','the pros and cons','利弊/正反两面','/ðə proʊz ænd kɒnz/','phrase','We must weigh the pros and cons.','我们必须权衡利弊。','C1','collocation'],
['c114','be attributed to','归因于','/bi əˈtrɪbjuːtɪd tuː/','phrase','The decline can be attributed to several factors.','下降可归因于几个因素。','C1','collocation'],
['c115','shed light on','阐明/揭示','/ʃed laɪt ɒn/','phrase','This study sheds light on the issue.','这项研究揭示了这个问题。','C1','collocation'],

// ── AWL 核心 60 词 ──
['awl001','analyse','分析','/ˈænəlaɪz/','v.','We need to analyse the data.','我们需要分析数据。','B1','awl'],
['awl002','approach','方法','/əˈproʊtʃ/','n.','Try a different approach.','试试不同的方法。','B1','awl'],
['awl003','assess','评估','/əˈses/','v.','We must assess the risks.','我们必须评估风险。','B1','awl'],
['awl004','assume','假设','/əˈsjuːm/','v.','Do not assume anything.','不要做任何假设。','B1','awl'],
['awl005','authority','权威','/ɔːˈθɒrəti/','n.','The authorities are investigating.','当局正在调查。','B1','awl'],
['awl006','concept','概念','/ˈkɒnsept/','n.','This is a difficult concept.','这是一个难懂的概念。','B1','awl'],
['awl007','consist','由...组成','/kənˈsɪst/','v.','The team consists of five members.','团队由五名成员组成。','B1','awl'],
['awl008','constitute','构成','/ˈkɒnstɪtjuːt/','v.','Women constitute 60 percent of the workforce.','女性占劳动力的60%。','B1','awl'],
['awl009','contract','合同','/ˈkɒntrækt/','n.','I signed a contract.','我签了一份合同。','B1','awl'],
['awl010','create','创造','/kriˈeɪt/','v.','We want to create a better future.','我们想创造更好的未来。','B1','awl'],
['awl011','data','数据','/ˈdeɪtə/','n.','The data supports this conclusion.','数据支持这个结论。','B1','awl'],
['awl012','define','定义','/dɪˈfaɪn/','v.','How do you define success?','你怎么定义成功？','B1','awl'],
['awl013','derive','源自','/dɪˈraɪv/','v.','The word derives from Latin.','这个词源自拉丁语。','B1','awl'],
['awl014','distribute','分配','/dɪˈstrɪbjuːt/','v.','Food was distributed to the poor.','食物被分发给穷人。','B1','awl'],
['awl015','establish','建立','/ɪˈstæblɪʃ/','v.','They established a new school.','他们建立了一所新学校。','B1','awl'],
['awl016','estimate','估计','/ˈestɪmeɪt/','v.','We estimate the cost at 1000 dollars.','我们估计费用为1000美元。','B1','awl'],
['awl017','evident','明显的','/ˈevɪdənt/','adj.','It is evident that change is needed.','很明显需要改变。','B1','awl'],
['awl018','export','出口','/ɪkˈspɔːrt/','v.','China exports many goods.','中国出口很多商品。','B1','awl'],
['awl019','factor','因素','/ˈfæktər/','n.','Cost is an important factor.','成本是重要因素。','B1','awl'],
['awl020','finance','金融','/ˈfaɪnæns/','n.','She works in finance.','她从事金融工作。','B1','awl'],
['awl021','formula','公式','/ˈfɔːrmjələ/','n.','There is no simple formula.','没有简单的公式。','B1','awl'],
['awl022','function','功能','/ˈfʌŋkʃən/','n.','What is the function of this button?','这个按钮的功能是什么？','B1','awl'],
['awl023','identify','识别','/aɪˈdentɪfaɪ/','v.','Can you identify the problem?','你能识别问题吗？','B1','awl'],
['awl024','income','收入','/ˈɪnkʌm/','n.','He has a high income.','他有高收入。','B1','awl'],
['awl025','indicate','表明','/ˈɪndɪkeɪt/','v.','The results indicate a problem.','结果表明有问题。','B1','awl'],
['awl026','individual','个人','/ˌɪndɪˈvɪdʒuəl/','n.','Each individual is unique.','每个个体都是独特的。','B1','awl'],
['awl027','interpret','解读','/ɪnˈtɜːrprɪt/','v.','How do you interpret this data?','你怎么解读这个数据？','B1','awl'],
['awl028','involve','涉及','/ɪnˈvɒlv/','v.','The job involves a lot of travel.','这份工作涉及大量出差。','B1','awl'],
['awl029','issue','议题','/ˈɪʃuː/','n.','This is a complex issue.','这是一个复杂问题。','B1','awl'],
['awl030','labour','劳动力','/ˈleɪbər/','n.','Manual labour is declining.','体力劳动在减少。','B1','awl'],
['awl031','legal','法律的','/ˈliːɡəl/','adj.','Is this legal?','这合法吗？','B1','awl'],
['awl032','legislate','立法','/ˈledʒɪsleɪt/','v.','The government should legislate on this.','政府应该对此立法。','B1','awl'],
['awl033','major','主要的','/ˈmeɪdʒər/','adj.','This is a major problem.','这是一个主要问题。','B1','awl'],
['awl034','method','方法','/ˈmeθəd/','n.','This method is effective.','这个方法有效。','B1','awl'],
['awl035','occur','发生','/əˈkɜːr/','v.','When did this occur?','这什么时候发生的？','B1','awl'],
['awl036','percent','百分比','/pərˈsent/','n.','Eighty percent agreed.','百分之八十同意了。','B1','awl'],
['awl037','period','时期','/ˈpɪəriəd/','n.','This is a difficult period.','这是一个困难时期。','B1','awl'],
['awl038','policy','政策','/ˈpɒləsi/','n.','The government changed its policy.','政府改变了政策。','B1','awl'],
['awl039','principle','原则','/ˈprɪnsɪpəl/','n.','I believe in this principle.','我相信这个原则。','B1','awl'],
['awl040','proceed','继续','/prəˈsiːd/','v.','Let us proceed with the plan.','我们继续执行计划。','B1','awl'],
['awl041','process','过程','/ˈproʊses/','n.','It is a long process.','这是一个漫长过程。','B1','awl'],
['awl042','require','需要','/rɪˈkwaɪər/','v.','This job requires patience.','这份工作需要耐心。','B1','awl'],
['awl043','research','研究','/rɪˈsɜːrtʃ/','n.','More research is needed.','需要更多研究。','B1','awl'],
['awl044','respond','回应','/rɪˈspɒnd/','v.','How should we respond?','我们该如何回应？','B1','awl'],
['awl045','role','作用','/roʊl/','n.','Education plays a key role.','教育起关键作用。','B1','awl'],
['awl046','section','部分','/ˈsekʃən/','n.','Read the first section.','读第一部分。','B1','awl'],
['awl047','sector','部门','/ˈsektər/','n.','The private sector is growing.','私营部门在增长。','B1','awl'],
['awl048','significant','显著的','/sɪɡˈnɪfɪkənt/','adj.','There was a significant increase.','有显著的增长。','B1','awl'],
['awl049','similar','相似的','/ˈsɪmɪlər/','adj.','These two are very similar.','这两个非常相似。','B1','awl'],
['awl050','source','来源','/sɔːrs/','n.','Cite your sources.','注明你的来源。','B1','awl'],
['awl051','specific','具体的','/spəˈsɪfɪk/','adj.','Can you be more specific?','你能更具体吗？','B1','awl'],
['awl052','structure','结构','/ˈstrʌktʃər/','n.','The essay has a clear structure.','文章结构清晰。','B1','awl'],
['awl053','theory','理论','/ˈθɪəri/','n.','In theory, this should work.','理论上这应该有效。','B1','awl'],
['awl054','vary','变化','/ˈveəri/','v.','Opinions vary on this issue.','对此问题意见不一。','B1','awl'],
['awl055','achieve','实现','/əˈtʃiːv/','v.','Set goals and achieve them.','设定目标并实现它们。','B2','awl'],
['awl056','acquire','获得','/əˈkwaɪər/','v.','Children acquire language naturally.','儿童自然习得语言。','B2','awl'],
['awl057','affect','影响','/əˈfekt/','v.','How does this affect you?','这如何影响你？','B2','awl'],
['awl058','appropriate','适当的','/əˈproʊpriət/','adj.','Is this appropriate?','这合适吗？','B2','awl'],
['awl059','aspect','方面','/ˈæspekt/','n.','Consider every aspect.','考虑每个方面。','B2','awl'],
['awl060','assist','帮助','/əˈsɪst/','v.','Can I assist you?','我能帮你吗？','B2','awl'],
['awl061','category','类别','/ˈkætəɡəri/','n.','This falls into a different category.','这属于不同的类别。','B2','awl'],
['awl062','community','社区','/kəˈmjuːnəti/','n.','Help your local community.','帮助你的本地社区。','B2','awl'],
['awl063','complex','复杂的','/ˈkɒmpleks/','adj.','This is a complex issue.','这是一个复杂问题。','B2','awl'],
['awl064','conclude','总结','/kənˈkluːd/','v.','What can we conclude?','我们能得出什么结论？','B2','awl'],
['awl065','conduct','进行','/kənˈdʌkt/','v.','They conducted a survey.','他们进行了一项调查。','B2','awl'],
['awl066','consequence','后果','/ˈkɒnsɪkwəns/','n.','Consider the consequences.','考虑后果。','B2','awl'],
['awl067','construct','建造','/kənˈstrʌkt/','v.','They constructed a new building.','他们建了一栋新楼。','B2','awl'],
['awl068','consume','消费','/kənˈsjuːm/','v.','We consume too much energy.','我们消耗太多能源。','B2','awl'],
['awl069','culture','文化','/ˈkʌltʃər/','n.','Learn about different cultures.','了解不同的文化。','B2','awl'],
['awl070','design','设计','/dɪˈzaɪn/','v.','Who designed this building?','谁设计了这栋建筑？','B2','awl'],
['awl071','distinct','明显的','/dɪˈstɪŋkt/','adj.','There is a distinct difference.','有明显区别。','B2','awl'],
['awl072','evaluate','评估','/ɪˈvæljueɪt/','v.','We need to evaluate the results.','我们需要评估结果。','B2','awl'],
['awl073','feature','特征','/ˈfiːtʃər/','n.','What are the key features?','关键特征是什么？','B2','awl'],
['awl074','focus','焦点','/ˈfoʊkəs/','n.','Focus on what matters.','专注于重要的事。','B2','awl'],
['awl075','impact','影响','/ˈɪmpækt/','n.','The impact was significant.','影响很显著。','B2','awl'],
['awl076','invest','投资','/ɪnˈvest/','v.','Invest in your future.','投资你的未来。','B2','awl'],
['awl077','maintain','维持','/meɪnˈteɪn/','v.','Maintain a healthy lifestyle.','保持健康的生活方式。','B2','awl'],
['awl078','obtain','获得','/əbˈteɪn/','v.','How can I obtain a visa?','我怎样才能获得签证？','B2','awl'],
['awl079','participate','参与','/pɑːrˈtɪsɪpeɪt/','v.','Everyone should participate.','每个人都应该参与。','B2','awl'],
['awl080','perceive','感知','/pərˈsiːv/','v.','How do you perceive this situation?','你怎么看待这个情况？','B2','awl'],
['awl081','positive','积极的','/ˈpɒzətɪv/','adj.','Stay positive.','保持积极。','B2','awl'],
['awl082','potential','潜力','/pəˈtenʃəl/','n.','She has great potential.','她有巨大潜力。','B2','awl'],
['awl083','previous','之前的','/ˈpriːviəs/','adj.','My previous job was in sales.','我之前的工作是销售。','B2','awl'],
['awl084','primary','主要的','/ˈpraɪməri/','adj.','The primary goal is education.','首要目标是教育。','B2','awl'],
['awl085','purchase','购买','/ˈpɜːrtʃəs/','v.','I want to purchase a ticket.','我想买一张票。','B2','awl'],
['awl086','range','范围','/reɪndʒ/','n.','A wide range of options is available.','有广泛的选择。','B2','awl'],
['awl087','region','地区','/ˈriːdʒən/','n.','This region is known for tea.','这个地区以茶闻名。','B2','awl'],
['awl088','regulate','管理','/ˈreɡjuleɪt/','v.','Laws regulate this industry.','法律监管这个行业。','B2','awl'],
['awl089','relevant','相关的','/ˈreləvənt/','adj.','Is this relevant?','这相关吗？','B2','awl'],
['awl090','resource','资源','/rɪˈzɔːrs/','n.','Natural resources are limited.','自然资源是有限的。','B2','awl'],
['awl091','restrict','限制','/rɪˈstrɪkt/','v.','The law restricts smoking.','法律限制吸烟。','B2','awl'],
['awl092','seek','寻求','/siːk/','v.','We seek a solution.','我们寻求解决方案。','B2','awl'],
['awl093','select','选择','/sɪˈlekt/','v.','Select the best option.','选择最佳选项。','B2','awl'],
['awl094','strategy','策略','/ˈstrætədʒi/','n.','We need a new strategy.','我们需要新策略。','B2','awl'],
['awl095','survey','调查','/ˈsɜːrveɪ/','n.','The survey showed interesting results.','调查显示了有趣的结果。','B2','awl'],
['awl096','tradition','传统','/trəˈdɪʃən/','n.','This is an old tradition.','这是一个古老的传统。','B2','awl'],
['awl097','transfer','转移','/trænsˈfɜːr/','v.','Transfer money between accounts.','在账户之间转账。','B2','awl'],

// ── AWL 续 70 词 ──
['awl101','access','获取','/ˈækses/','n./v.','Everyone should have access to education.','每个人都应有受教育的机会。','B1','awl'],
['awl102','adequate','足够的','/ˈædɪkwət/','adj.','The supply is not adequate.','供应不足。','B2','awl'],
['awl103','adjust','调整','/əˈdʒʌst/','v.','We need to adjust our plan.','我们需要调整计划。','B1','awl'],
['awl104','alter','改变','/ˈɔːltər/','v.','This will alter the outcome.','这将改变结果。','B1','awl'],
['awl105','ambiguity','歧义','/ˌæmbɪˈɡjuːəti/','n.','The ambiguity caused confusion.','歧义导致了混乱。','B2','awl'],
['awl106','amend','修改','/əˈmend/','v.','The law was amended.','法律被修改了。','B2','awl'],
['awl107','apparent','明显的','/əˈpærənt/','adj.','It is apparent that change is needed.','很明显需要改变。','B2','awl'],
['awl108','appendix','附录','/əˈpendɪks/','n.','See the appendix for details.','详见附录。','B2','awl'],
['awl109','arbitrary','任意的','/ˈɑːrbɪtrəri/','adj.','The decision seemed arbitrary.','这个决定似乎很武断。','B2','awl'],
['awl110','automate','自动化','/ˈɔːtəmeɪt/','v.','The process has been automated.','流程已自动化。','B2','awl'],
['awl111','bias','偏见','/ˈbaɪəs/','n.','The study had a clear bias.','这项研究有明显偏见。','B2','awl'],
['awl112','brief','简短的','/briːf/','adj.','Give a brief summary.','做一个简短总结。','B2','awl'],
['awl113','capable','有能力的','/ˈkeɪpəbəl/','adj.','She is capable of leading.','她有能力领导。','B1','awl'],
['awl114','cease','停止','/siːs/','v.','The factory ceased operations.','工厂停止了运营。','B2','awl'],
['awl115','channel','渠道','/ˈtʃænəl/','n.','We need better communication channels.','我们需要更好的沟通渠道。','B1','awl'],
['awl116','chart','图表','/tʃɑːrt/','n.','The chart shows the trend.','图表显示了趋势。','B1','awl'],
['awl117','chemical','化学的','/ˈkemɪkəl/','adj.','Chemical pollution is harmful.','化学污染是有害的。','B1','awl'],
['awl118','circumstance','情况','/ˈsɜːrkəmstæns/','n.','Under the circumstances, I agree.','在这种情况下我同意。','B1','awl'],
['awl119','cite','引用','/saɪt/','v.','Cite your sources properly.','正确引用你的来源。','B2','awl'],
['awl120','civil','公民的','/ˈsɪvəl/','adj.','Civil rights must be protected.','公民权利必须受到保护。','B2','awl'],
['awl121','clarify','澄清','/ˈklærɪfaɪ/','v.','Let me clarify my point.','让我澄清我的观点。','B1','awl'],
['awl122','classic','经典的','/ˈklæsɪk/','adj.','This is a classic example.','这是一个经典例子。','B1','awl'],
['awl123','clause','条款','/klɔːz/','n.','Read the contract clause carefully.','仔细阅读合同条款。','B2','awl'],
['awl124','code','代码/准则','/koʊd/','n.','This violates the code of conduct.','这违反了行为准则。','B1','awl'],
['awl125','coherent','连贯的','/koʊˈhɪərənt/','adj.','The essay was not coherent.','这篇文章不连贯。','B2','awl'],
['awl126','coincide','同时发生','/ˌkoʊɪnˈsaɪd/','v.','The two events coincided.','这两件事同时发生。','B2','awl'],
['awl127','collapse','崩溃','/kəˈlæps/','v.','The system could collapse.','系统可能崩溃。','B2','awl'],
['awl128','colleague','同事','/ˈkɒliːɡ/','n.','I discussed it with my colleague.','我和同事讨论过。','B1','awl'],
['awl129','commence','开始','/kəˈmens/','v.','The meeting will commence at 9 AM.','会议将于上午9点开始。','B2','awl'],
['awl130','comment','评论','/ˈkɒment/','n.','Do you have any comments?','你有什么评论吗？','B1','awl'],
['awl131','commission','委员会','/kəˈmɪʃən/','n.','A commission was established.','成立了一个委员会。','B1','awl'],
['awl132','commit','承诺/犯罪','/kəˈmɪt/','v.','We must commit to change.','我们必须承诺改变。','B1','awl'],
['awl133','commodity','商品','/kəˈmɒdəti/','n.','Oil is a valuable commodity.','石油是一种有价值的商品。','B2','awl'],
['awl134','communicate','沟通','/kəˈmjuːnɪkeɪt/','v.','We need to communicate better.','我们需要更好地沟通。','B1','awl'],
['awl135','compensate','补偿','/ˈkɒmpənseɪt/','v.','The company compensated the victims.','公司赔偿了受害者。','B1','awl'],
['awl136','compile','汇编','/kəmˈpaɪl/','v.','We compiled a list of resources.','我们汇编了一份资源清单。','B2','awl'],
['awl137','complement','补充','/ˈkɒmplɪment/','v.','The two skills complement each other.','这两种技能相互补充。','B2','awl'],
['awl138','component','组成部分','/kəmˈpoʊnənt/','n.','This is a key component.','这是一个关键组成部分。','B1','awl'],
['awl139','compound','复合的','/ˈkɒmpaʊnd/','adj.','This is a compound word.','这是一个复合词。','B1','awl'],
['awl140','comprise','包含','/kəmˈpraɪz/','v.','The team comprises five experts.','团队由五名专家组成。','B2','awl'],
['awl141','compute','计算','/kəmˈpjuːt/','v.','The system can compute this quickly.','系统可以快速计算。','B2','awl'],
['awl142','conceive','构想','/kənˈsiːv/','v.','He conceived a brilliant idea.','他构想了一个绝妙的主意。','B2','awl'],
['awl143','concentrate','集中','/ˈkɒnsəntreɪt/','v.','I cannot concentrate with noise.','有噪音我无法集中注意力。','B1','awl'],
['awl144','concurrent','同时的','/kənˈkʌrənt/','adj.','The two events were concurrent.','这两件事是同时发生的。','B2','awl'],
['awl145','confine','限制','/kənˈfaɪn/','v.','Do not confine yourself to one solution.','不要局限于一种解决方案。','B2','awl'],
['awl146','confirm','确认','/kənˈfɜːrm/','v.','Please confirm your attendance.','请确认你的出席。','B1','awl'],
['awl147','conflict','冲突','/ˈkɒnflɪkt/','n.','There is a conflict between the two sides.','双方之间存在冲突。','B1','awl'],
['awl148','conform','遵守','/kənˈfɔːrm/','v.','You must conform to the rules.','你必须遵守规则。','B2','awl'],
['awl149','consent','同意','/kənˈsent/','n.','You need parental consent.','你需要父母同意。','B2','awl'],
['awl150','consequent','随之发生的','/ˈkɒnsɪkwənt/','adj.','The consequent damage was severe.','随之而来的损害很严重。','B2','awl'],
['awl151','considerable','相当大的','/kənˈsɪdərəbəl/','adj.','A considerable amount of money was spent.','花了相当大一笔钱。','B1','awl'],
['awl152','constant','持续的','/ˈkɒnstənt/','adj.','The noise was constant.','噪音持续不断。','B1','awl'],
['awl153','constrain','限制','/kənˈstreɪn/','v.','Budget constraints limited the project.','预算限制了这个项目。','B2','awl'],
['awl154','consult','咨询','/kənˈsʌlt/','v.','You should consult a doctor.','你应该咨询医生。','B1','awl'],
['awl155','contact','联系','/ˈkɒntækt/','n./v.','I lost contact with him.','我和他失去了联系。','B1','awl'],
['awl156','contemporary','当代的','/kənˈtempərəri/','adj.','This is a contemporary issue.','这是一个当代问题。','B2','awl'],
['awl157','contradict','矛盾','/ˌkɒntrəˈdɪkt/','v.','The two statements contradict each other.','这两个说法相互矛盾。','B2','awl'],
['awl158','contribute','贡献','/kənˈtrɪbjuːt/','v.','Everyone can contribute to society.','每个人都能为社会做贡献。','B1','awl'],
['awl159','controversy','争议','/ˈkɒntrəvɜːrsi/','n.','The policy caused controversy.','这项政策引起了争议。','B2','awl'],
['awl160','convene','召集','/kənˈviːn/','v.','The committee will convene next week.','委员会将于下周召开。','B2','awl'],
['awl161','converse','相反的','/ˈkɒnvɜːrs/','adj.','The converse is also true.','反之亦然。','B2','awl'],
['awl162','convert','转换','/kənˈvɜːrt/','v.','Convert the file to PDF.','将文件转换为PDF。','B1','awl'],
['awl163','convince','说服','/kənˈvɪns/','v.','I tried to convince him.','我试图说服他。','B1','awl'],
['awl164','cooperate','合作','/koʊˈɒpəreɪt/','v.','We must cooperate to succeed.','我们必须合作才能成功。','B1','awl'],
['awl165','coordinate','协调','/koʊˈɔːrdɪneɪt/','v.','We need to coordinate our efforts.','我们需要协调我们的努力。','B2','awl'],
['awl166','core','核心','/kɔːr/','n.','This is the core of the problem.','这是问题的核心。','B1','awl'],
['awl167','corporate','公司的','/ˈkɔːrpərət/','adj.','Corporate culture is important.','公司文化很重要。','B2','awl'],
['awl168','correspond','对应','/ˌkɒrɪˈspɒnd/','v.','The numbers do not correspond.','数字对不上。','B1','awl'],
['awl169','couple','一对/几个','/ˈkʌpəl/','n.','I need a couple of days.','我需要几天时间。','B1','awl'],
['awl170','crucial','至关重要的','/ˈkruːʃəl/','adj.','This decision is crucial.','这个决定至关重要。','B2','awl'],

// ── 雅思高频话题词 80 词 ──
['top001','biodiversity','生物多样性','/ˌbaɪoʊdaɪˈvɜːrsəti/','n.','Biodiversity is essential for ecosystems.','生物多样性对生态系统至关重要。','A2','environment'],
['top002','carbon','碳','/ˈkɑːrbən/','n.','Reducing carbon emissions is vital.','减少碳排放至关重要。','A2','environment'],
['top003','deforestation','森林砍伐','/diːˌfɒrɪˈsteɪʃən/','n.','Deforestation threatens wildlife.','森林砍伐威胁野生动物。','B1','environment'],
['top004','ecosystem','生态系统','/ˈiːkoʊsɪstəm/','n.','The ecosystem is fragile.','生态系统很脆弱。','B1','environment'],
['top005','emission','排放','/ɪˈmɪʃən/','n.','Carbon emissions must be reduced.','必须减少碳排放。','B1','environment'],
['top006','endangered','濒危的','/ɪnˈdeɪndʒərd/','adj.','Many species are endangered.','许多物种濒危。','A2','environment'],
['top007','fossil fuel','化石燃料','/ˈfɒsəl fjuːəl/','n.','We must move away from fossil fuels.','我们必须摆脱化石燃料。','B1','environment'],
['top008','greenhouse','温室','/ˈɡriːnhaʊs/','n.','The greenhouse effect causes warming.','温室效应导致变暖。','B1','environment'],
['top009','habitat','栖息地','/ˈhæbɪtæt/','n.','The habitat is being destroyed.','栖息地正在被破坏。','A2','environment'],
['top010','renewable','可再生的','/rɪˈnjuːəbəl/','adj.','Solar power is renewable energy.','太阳能是可再生能源。','A2','environment'],
['top011','curriculum','课程','/kəˈrɪkjələm/','n.','The curriculum needs updating.','课程需要更新。','B1','education'],
['top012','discipline','纪律/学科','/ˈdɪsɪplɪn/','n.','Discipline is essential in schools.','纪律在学校至关重要。','B1','education'],
['top013','literacy','读写能力','/ˈlɪtərəsi/','n.','Literacy rates are improving.','识字率在提高。','B1','education'],
['top014','pedagogy','教学法','/ˈpedəɡɒdʒi/','n.','Modern pedagogy focuses on the learner.','现代教学法以学习者为中心。','C1','education'],
['top015','scholarship','奖学金','/ˈskɒlərʃɪp/','n.','She won a scholarship to study abroad.','她获得了留学奖学金。','B1','education'],
['top016','vocational','职业的','/voʊˈkeɪʃənəl/','adj.','Vocational training is important.','职业培训很重要。','B1','education'],
['top017','algorithm','算法','/ˈælɡərɪðəm/','n.','Algorithms control what we see online.','算法控制着我们在网上看到的内容。','B2','technology'],
['top018','artificial','人工的','/ˌɑːrtɪˈfɪʃəl/','adj.','Artificial intelligence is advancing rapidly.','人工智能正在快速发展。','B1','technology'],
['top019','automation','自动化','/ˌɔːtəˈmeɪʃən/','n.','Automation threatens some jobs.','自动化威胁到一些工作。','B1','technology'],
['top020','bandwidth','带宽','/ˈbændwɪdθ/','n.','The bandwidth is insufficient.','带宽不足。','B2','technology'],
['top021','breakthrough','突破','/ˈbreɪkθruː/','n.','This is a major breakthrough.','这是一个重大突破。','B2','technology'],
['top022','cybersecurity','网络安全','/ˌsaɪbərsɪˈkjʊrəti/','n.','Cybersecurity is a growing concern.','网络安全是一个日益严重的问题。','B2','technology'],
['top023','database','数据库','/ˈdeɪtəbeɪs/','n.','The database contains millions of records.','该数据库包含数百万条记录。','B1','technology'],
['top024','gadget','小设备','/ˈɡædʒɪt/','n.','Everyone carries smart gadgets now.','现在人人都带着智能设备。','A2','technology'],
['top025','innovative','创新的','/ˈɪnəveɪtɪv/','adj.','This is an innovative solution.','这是一个创新的解决方案。','B1','technology'],
['top026','obsolete','过时的','/ˈɒbsəliːt/','adj.','This technology is becoming obsolete.','这项技术正在过时。','B2','technology'],
['top027','telecommunications','电信','/ˌtelɪkəˌmjuːnɪˈkeɪʃənz/','n.','Telecommunications have transformed business.','电信已经改变了商业。','B2','technology'],
['top028','demographic','人口的','/ˌdeməˈɡræfɪk/','adj.','Demographic changes affect the economy.','人口变化影响经济。','B2','society'],
['top029','diversity','多样性','/daɪˈvɜːrsəti/','n.','Cultural diversity enriches society.','文化多样性丰富社会。','B1','society'],
['top030','equality','平等','/ɪˈkwɒləti/','n.','We must strive for equality.','我们必须争取平等。','B1','society'],
['top031','ethnic','民族的','/ˈeθnɪk/','adj.','Ethnic minorities need protection.','少数民族需要保护。','B2','society'],
['top032','gender','性别','/ˈdʒendər/','n.','Gender equality is a fundamental right.','性别平等是一项基本权利。','B1','society'],
['top033','migration','迁移','/maɪˈɡreɪʃən/','n.','Migration patterns have changed.','迁移模式已改变。','B1','society'],
['top034','minority','少数','/maɪˈnɒrəti/','n.','Minority rights must be respected.','少数群体权利必须得到尊重。','B1','society'],
['top035','poverty','贫困','/ˈpɒvərti/','n.','Poverty remains a global challenge.','贫困仍是一个全球性挑战。','B1','society'],
['top036','prejudice','偏见','/ˈpredʒədɪs/','n.','We must overcome prejudice.','我们必须克服偏见。','B2','society'],
['top037','urbanization','城市化','/ˌɜːrbənaɪˈzeɪʃən/','n.','Urbanization is accelerating worldwide.','城市化正在全球加速。','B1','society'],
['top038','diagnosis','诊断','/ˌdaɪəɡˈnoʊsɪs/','n.','Early diagnosis can save lives.','早期诊断可以挽救生命。','B1','health'],
['top039','epidemic','流行病','/ˌepɪˈdemɪk/','n.','The epidemic spread rapidly.','流行病迅速蔓延。','B2','health'],
['top040','immunity','免疫力','/ɪˈmjuːnəti/','n.','Vaccines build immunity.','疫苗建立免疫力。','B2','health'],
['top041','mental','心理的','/ˈmentəl/','adj.','Mental health is as important as physical health.','心理健康和身体健康同样重要。','B1','health'],
['top042','obesity','肥胖','/oʊˈbiːsəti/','n.','Obesity rates are rising among children.','儿童肥胖率在上升。','B1','health'],
['top043','pharmaceutical','制药的','/ˌfɑːrməˈsuːtɪkəl/','adj.','The pharmaceutical industry is highly regulated.','制药行业受到严格监管。','B2','health'],
['top044','sedentary','久坐的','/ˈsedənteri/','adj.','A sedentary lifestyle causes health problems.','久坐的生活方式导致健康问题。','B2','health'],
['top045','therapy','治疗','/ˈθerəpi/','n.','Physical therapy helped her recover.','物理治疗帮助她康复。','B1','health'],
['top046','workforce','劳动力','/ˈwɜːrkfɔːrs/','n.','The workforce is changing rapidly.','劳动力正在快速变化。','B1','work'],
['top047','entrepreneur','企业家','/ˌɒntrəprəˈnɜːr/','n.','Entrepreneurs drive innovation.','企业家推动创新。','B2','work'],
['top048','freelance','自由职业','/ˈfriːlæns/','adj.','Freelance work is becoming common.','自由职业正变得普遍。','B2','work'],
['top049','internship','实习','/ˈɪntɜːrnʃɪp/','n.','She completed a summer internship.','她完成了一个暑期实习。','B1','work'],
['top050','profession','职业','/prəˈfeʃən/','n.','Teaching is a noble profession.','教书是一个崇高的职业。','B1','work'],
['top051','recruitment','招聘','/rɪˈkruːtmənt/','n.','The recruitment process takes time.','招聘过程需要时间。','B1','work'],
['top052','revenue','收入','/ˈrevənjuː/','n.','The company generated high revenue.','公司产生了高收入。','B1','work'],
['top053','subsidy','补贴','/ˈsʌbsɪdi/','n.','Government subsidies support farmers.','政府补贴支持农民。','B2','work'],
['top054','turnover','营业额/离职率','/ˈtɜːrnoʊvər/','n.','Staff turnover is high in this industry.','这个行业的员工流动率很高。','B2','work'],
['top055','heritage','遗产','/ˈherɪtɪdʒ/','n.','Cultural heritage must be preserved.','文化遗产必须得到保护。','B1','culture'],
['top056','indigenous','本土的','/ɪnˈdɪdʒɪnəs/','adj.','Indigenous cultures are disappearing.','本土文化正在消失。','B2','culture'],
['top057','multicultural','多元文化的','/ˌmʌltiˈkʌltʃərəl/','adj.','We live in a multicultural society.','我们生活在一个多元文化社会。','B1','culture'],
['top058','preserve','保护','/prɪˈzɜːrv/','v.','We must preserve our traditions.','我们必须保护我们的传统。','B1','culture'],
['top059','ritual','仪式','/ˈrɪtʃuəl/','n.','The ritual has been practiced for centuries.','这个仪式已经实践了几个世纪。','B2','culture'],
['top060','tourism','旅游业','/ˈtʊərɪzəm/','n.','Tourism boosts the local economy.','旅游业促进本地经济。','A2','culture'],
['top061','budget','预算','/ˈbʌdʒɪt/','n.','We need to stay within budget.','我们需要控制在预算内。','B1','economy'],
['top062','currency','货币','/ˈkʌrənsi/','n.','The local currency is the yuan.','当地货币是人民币。','B1','economy'],
['top063','deficit','赤字','/ˈdefɪsɪt/','n.','The trade deficit is widening.','贸易逆差在扩大。','B2','economy'],
['top064','inflation','通货膨胀','/ɪnˈfleɪʃən/','n.','Inflation erodes purchasing power.','通货膨胀侵蚀购买力。','B1','economy'],
['top065','infrastructure','基础设施','/ˈɪnfrəstrʌktʃər/','n.','The city needs better infrastructure.','城市需要更好的基础设施。','B2','economy'],
['top066','monopoly','垄断','/məˈnɒpəli/','n.','The company has a monopoly on the market.','该公司垄断了市场。','B2','economy'],
['top067','prosperity','繁荣','/prɒˈsperəti/','n.','Education leads to prosperity.','教育带来繁荣。','B1','economy'],
['top068','tariff','关税','/ˈtærɪf/','n.','Tariffs protect domestic industries.','关税保护国内产业。','B2','economy'],
['top069','tourism','旅游业','/ˈtʊərɪzəm/','n.','Tourism is a major source of income.','旅游业是主要收入来源。','A2','economy'],
['top070','wellbeing','幸福/福祉','/ˌwelˈbiːɪŋ/','n.','Employee wellbeing is a priority.','员工福祉是优先事项。','B1','health'],
];

export const IELTS_VOCAB: VocabWord[] = raw.map(([id,word,chinese,phonetic,pos,example,exampleCN,level,topic]) =>
  ({id,word,chinese,phonetic,pos,example,exampleCN,level,topic}));
